<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>0c6770df-c5d3-48dc-903f-684b7a83fae0</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 42 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
