<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>2ddf83d0-d368-4ba0-9e09-8ddfc10a4773</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to age + 1;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
